- hosts: server
  become: true
  gather_facts: true
  
  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-1.8.0-openjdk
    
    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: update all packages 
    yum:
      name: '*'
      update_only: yes
      update_cache: yes
      state: latest
  - name: install  nano  
    yum:
      name: nano
      state: installed

  - name: install wget
    yum:
      name: wget
      state: installed 

  - name: Install epel release
    yum: 
      name: epel-release
      state: installed

  # Disabling warnings
  - name: Using curl to connect to a host via SOCKS proxy (unsupported in uri). Ordinarily this would throw a warning.
    shell: curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
    args:
      warn: no

  - name: install the nginx rpm from a remote repo
    
    shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key 
    args:
      warn: no

  - name: install jenkins
    yum:
      name: jenkins
      state: installed

  - name: Restart service httpd, in all cases
    service:
      name: jenkins
      state: restarted

  - name: Enable service httpd, and not touch the state
    service:
      name: jenkins
      enabled: yes

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: geerlingguy.java
    
